# Generated by Django 3.1.5 on 2021-09-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=255)),
            ],
        ),
    ]
